

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./backend:/usr/src/app
    networks:
      - student-network

  frontend:
    build: ./frontend
    ports:
      - "19000:19000"  # Expo DevTools
      - "19001:19001"  # Expo React Native debugger
      - "19002:19002"  # Expo tools
      - "8085:8081"   # Metro Bundler (bundle JS)
    environment:
      - API_BASE_URL=http://backend:3000
    volumes:
    
      - ./frontend:/app
      - /app/node_modules
    networks:
      - student-network
    depends_on:
      - backend

networks:
  student-network:
    driver: bridge
