---
- name: Déployer l'application Student Absence sur Kubernetes
  hosts: localhost
  become: false
  tasks:

    - name: Appliquer les manifests Kubernetes
      shell: kubectl apply -f /var/jenkins_home/workspace/test/k8s/